# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: listing.proto for package 'Listing'

require 'grpc'
require 'protobuf/listing_pb'

module Listing
  module ProductListingService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'Listing.ProductListingService'

      rpc :GetDiscount, ListingRequest, ListingResponse
    end

    Stub = Service.rpc_stub_class
  end
end
